In [8]:
import matplotlib.pyplot as plt
import numpy as np
import cv2

In [11]:
def bsif(image, filter_size):
    # Divide the image into a grid of cells
    num_rows, num_cols = image.shape
    cell_rows, cell_cols = filter_size, filter_size
    num_cell_rows = num_rows // cell_rows
    num_cell_cols = num_cols // cell_cols

    # Initialize the feature vector
    features = np.zeros((num_cell_rows, num_cell_cols, cell_rows, cell_cols))

    # Iterate over each cell in the grid
    for i in range(num_cell_rows):
        for j in range(num_cell_cols):
            cell = image[i * cell_rows : (i + 1) * cell_rows, j * cell_cols : (j + 1) * cell_cols]

            # Compute the binary pattern for the cell
            pattern = np.where(cell > cell.mean(), 1, 0)
            features[i, j] = pattern

    return features

In [14]:
imgPath = "./test_img.png"
image = cv2.cvtColor(cv2.imread(imgPath), cv2.COLOR_BGR2GRAY)
a = bsif(image, 3)
print(a)

[[[[1. 1. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[0. 0. 0.]
   [1. 0. 0.]
   [1. 1. 1.]]

  [[0. 0. 0.]
   [0. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 0.]
   [1. 0. 0.]
   [1. 0. 0.]]

  [[0. 0. 1.]
   [0. 1. 1.]
   [0. 0. 1.]]

  [[0. 0. 0.]
   [0. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 1. 1.]
   [0. 0. 1.]
   [0. 0. 0.]]

  [[1. 1. 1.]
   [0. 1. 0.]
   [0. 0. 0.]]

  ...

  [[1. 0. 0.]
   [1. 0. 0.]
   [1. 0. 0.]]

  [[0. 1. 1.]
   [0. 0. 1.]
   [0. 0. 1.]]

  [[0. 1. 1.]
   [0. 1. 1.]
   [0. 0. 1.]]]


 [[[1. 1. 0.]
   [0. 0. 0.]
   [0. 0. 1.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [1. 0. 1.]]

  [[0. 1. 1.]
   [0. 1. 1.]
   [0. 1. 0.]]

  ...

  [[1. 1. 0.]
   [1. 1. 0.]
   [1. 1. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [1. 1. 1.]]

  [[0. 0. 1.]
   [0. 1. 1.]
   [1. 1. 1.]]]


 ...


 [[[1. 1. 1.]
   [0. 0. 1.]
   [0. 0. 1.]]

  [[0. 1. 1.]
   [0. 1. 1.]
   [0. 1. 1.]]

  [[0. 0. 0.]
   [0. 1. 1.]
   [0. 0. 0.]]

  ...

  [[1. 1. 1.]
   [1. 0. 0.]
   [1. 